config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'courses#index'
  resources :courses, except: %i[update edit destroy]
  get 'about', to: 'pages#about'
  get 'help', to: 'pages#help'
  get 'contact_us', to: 'pages#contact_us'
  resources :students, except: [:destroy]
  get 'login', to: 'logins#new'
  post 'login', to: 'logins#create'
  delete 'logout', to: 'logins#destroy'
  post 'course_enroll', to: 'student_courses#create'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
# frozen_string_literal: true

class Course < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :short_name, presence: true, length: { minimum: 3, maximum: 15 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  has_many :student_courses
  has_many :students, through: :student_courses
end

app/models/student.rb
# frozen_string_literal: true

class Student < ApplicationRecord
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 105 },
                    uniqueness: { case_sensitive: false },
                    format: { with: VALID_EMAIL_REGEX }

  has_secure_password

  has_many :student_courses
  has_many :courses, through: :student_courses
end

app/models/student_course.rb
# frozen_string_literal: true

class StudentCourse < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :require_user

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Student.find(session[:student_id]) if session[:student_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    unless logged_in?
      flash[:notice] = 'You must be looged in to perform that action'
      redirect_to login_path
    end
  end
end

app/controllers/courses_controller.rb
# frozen_string_literal: true

class CoursesController < ApplicationController
  skip_before_action :require_user, except: %i[new create]

  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)
    if @course.save
      flash[:notice] = t(:success_create, course_name: @course.name)
      redirect_to @course
    else
      render 'new'
    end
  end

  private

  def course_params
    params.require(:course).permit(:name, :short_name, :description)
  end
end

app/controllers/logins_controller.rb
# frozen_string_literal: true

class LoginsController < ApplicationController
  skip_before_action :require_user, only: %i[new create]

  def new; end

  def create
    student = Student.find_by(email: params[:logins][:email].downcase)

    if student&.authenticate(params[:logins][:password])
      session[:student_id] = student.id
      flash[:notice] = t('.success_log_in')
      redirect_to student
    else
      flash.now[:notice] = t('.something_was_wrong')
      render 'new'
    end
  end

  def destroy
    session[:student_id] = nil
    flash[:notice] = t('.success_log_out')
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  def about; end

  def help; end

  def contact_us; end
end

app/controllers/student_courses_controller.rb
# frozen_string_literal: true

class StudentCoursesController < ApplicationController
  def create
    course_to_add = Course.find(params[:course_id])
    if current_user.courses.include?(course_to_add)
      flash[:notice] = 'Something was wrong with your enrollment'
      redirect_to root_path
    else
      StudentCourse.create(course: course_to_add, student: current_user)
      flash[:notice] = t(:success_enroll, course_name: course_to_add.name)
      redirect_to current_user
    end
  end
end

app/controllers/students_controller.rb
# frozen_string_literal: true

class StudentsController < ApplicationController
  skip_before_action :require_user
  before_action :set_student, only: %i[show edit update]
  before_action :require_same_student, only: %i[edit update]

  def index
    @students = Student.all
  end

  def show; end

  def new
    @student = Student.new
  end

  def create
    @student = Student.new(student_params)
    if @student.save
      flash[:notice] = t('.success_sign_up')
      redirect_to @student
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @student.update(student_params)
      flash[:notice] = t('.success_updated_profile')
      redirect_to @student
    else
      render 'edit'
    end
  end

  private

  def student_params
    params.require(:student).permit(:name, :email, :password, :password_confirmation)
  end

  def set_student
    @student = Student.find(params[:id])
  end

  def require_same_student
    if current_user != @student
      flash[:notice] = t('.edit_own_profile')
      redirect_to student_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def session_link
    if logged_in?
      link_to t('.log_out'), logout_path, method: :delete
    else
      link_to t('.log_in'), login_path
    end
  end
end

app/views/courses/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align"><%= t('.course_listings') %></h3>
  </div>
</div>

<div class="row">
  <% @courses.each do |course| %>
    <%= content_tag :div, class: "col s6 m6", data: { qa: course.id } do %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= course.name %></span>
          <p><%= t('.course_id') %>: <%= course.short_name %></p>
        </div>
        <div class="card-action">
          <% if logged_in? && !(current_user.courses.include?(course)) %>
            <%= link_to t('.enroll'), course_enroll_path(course_id: course.id), method: :post %>
          <% end %>
          <%= link_to t('.info'), course_path(course) %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/courses/new.html.erb
<%= render 'shared/errors', obj: @course %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= t('.create_new_course') %></h3>
        <div class="row">
          <%= form_for(@course, html: { class: "col s12" }) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder: t('.enter_course_name'), autofocus: true %>
                <%= f.label :name, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :short_name, placeholder: t('.enter_course_short_name') %>
                <%= f.label :short_name, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :description, placeholder: t('.enter_course_description') %>
                <%= f.label :description, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button("<i class=\"material-icons right\">arrow_forward</i>#{t('.create_course_button')}".html_safe,
                    class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/courses/show.html.erb
<div class="row sign-up-form">
  <div class="col s6 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @course.name %></span>
      </div>
    </div>
  </div>
  <div class="col s6 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <p><%= t('.description') %>:</p>
        <p><%= @course.description %></p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text"><%= t('.tech_university') %></h5>
        <p class="grey-text text-lighten-4"><%= t('.tech_university_desc') %>.</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text"><%= t('.information') %></h5>
        <ul>
          <li><%= link_to t('.help'), help_path, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to t('.about'), about_path, class: "grey-text text-lighten-3" %></li>
          <li><%= link_to t('.contact_us'), contact_us_path, class: "grey-text text-lighten-3" %></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      <div class="grey-text text-lighten-4 right">&copy; <%= Time.current.year %> <%= t('.tech_university_copy') %></div>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <% if logged_in? %>
      <li><%= link_to t('.your_profile'), student_path(current_user) %></li>
      <li><%= link_to t('.edit_profile'), edit_student_path(current_user) %></li>
      <li class="divider"></li>
    <% end %>
    <li><%= session_link %></li>
  </ul>
  <nav>
    <div class="container">
      <div class="nav-wrapper">
        <%= link_to t('.tech_university'), root_path, class: "brand-logo" %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to t('.courses'), root_path %></li>
          <% if logged_in? %>
            <li><%= link_to t('.students'), students_path %></li>
          <% end %>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1"><%= t('.account') %><i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <% flash.each do |key, message| %>
    <div class="container">
      <div class="row sign-up-form">
        <div class="col s12 m12 l12">
          <div class="card-panel red lighten-2" id="fade-out-target">
            <span class="white-text">
              <%= message %>
            </span>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/logins/new.html.erb
<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= t('.log_in_title') %></h3>
        <div class="row">
          <%= form_for(:logins, html: { class: "col s12" }) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: t('.enter_your_email_address'), autofocus: true %>
                <%= f.label :email %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: t('.enter_your_password') %>
                <%= f.label :password, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button "<i class=\"material-icons right\">arrow_forward</i>#{t('.log_in_button')}".html_safe,
                    class: "btn orange waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align"><%= t('.about_title') %></h3>
  </div>
</div>

<div class="row">
  <div class="col s6 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <p><%= t('.about_desc') %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/contact_us.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align"><%= t('.contact_us_title') %></h3>
  </div>
</div>

<div class="row">
  <div class="col s6 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <p><%= t('.contact_us_desc') %></p>
      </div>
    </div>
  </div>
</div>

app/views/pages/help.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align"><%= t('.help_title') %></h3>
  </div>
</div>

<div class="row">
  <div class="col s6 m12">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <p><%= t('.help_desc') %></p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="container">
    <div class="row sign-up-form">
      <div class="col s12 m12 l12">
        <div class="card-panel red lighten-2">
          <span class="white-text">
            <strong><%= pluralize(obj.errors.count, "error") %></strong>
            prohibited your profile from being created
            <ul>
              <% obj.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </span>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/students/_form.html.erb
<%= render 'shared/errors', obj: @student %>

<div class="container">
  <div class="row center sign-up-form">
    <div class="col s12 m12 l12">
      <div class="card-panel">
        <h3 class="header"><%= @student.new_record? ? t('.sign_up_title') : t('.edit_your_profile_title') %></h3>
        <div class="row">
          <%= form_for(@student, html: { class: "col s12" }) do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.text_field :name, placeholder:  t('.enter_your_full_name'), autofocus: true %>
                <%= f.label :name, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.email_field :email, placeholder: t('.enter_your_full_address') %>
                <%= f.label :email, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password, placeholder: t('.choose_a_password') %>
                <%= f.label :password, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.password_field :password_confirmation, placeholder: t('.confirm_your_password') %>
                <%= f.label :password_confirmation, class: 'active' %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.button(@student.new_record? ? "<i class=\"material-icons right\">arrow_forward</i>#{t('.sign_up_title')}".html_safe :
                    "<i class=\"material-icons right\">arrow_forward</i>#{t('.submit_updates')}".html_safe,
                    class: "btn orange waves-effect waves-light right") %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/students/edit.html.erb
<%= render 'form' %>

app/views/students/index.html.erb
<div class="row">
  <div class="col s12">
    <h3 class="center-align"><%= t('.students_directory') %></h3>
  </div>
</div>

<div class="row">
  <% @students.each do |student| %>
    <%= content_tag :div, class: "col s6 m6", data: { qa: student.id } do %>
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"><%= student.name %></span>
          <p><%= student.email %></p>
          <% if student.courses.count > 0 %>
            <p><%= t('.course_enrollments') %>:  <%= student.courses.count %></p>
          <% else %>
            <p><%= t('.course_enrollments') %>: <%= t('.none') %></p>
          <% end %>
        </div>
        <div class="card-action">
          <%= link_to t('.view_profile'), student_path(student) %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/students/new.html.erb
<%= render 'form' %>

app/views/students/show.html.erb
<div class="row sign-up-form">
  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= @student.name %></span>
        <p><%= @student.email %></p>
      </div>
    </div>
    <% if current_user == @student %>
      <%= link_to "<i class=\"material-icons right\">create</i>#{t('.edit_your_profile')}".html_safe,
          edit_student_path(@student), class: "waves-effect waves-light btn" %>
    <% end %>
  </div>

  <div class="col s6 m6">
    <div class="card blue-grey darken-1">
      <div class="card-content white-text">
        <span class="card-title"><%= t('.course_enrollments') %>:</span>
          <% if @student.courses.empty? %>
            <%= t('.none') %>
          <% else %>
            <ul>
              <% @student.courses.each do |course| %>
                <%= content_tag :li, class: "grey-text text-lighten-3", data: { qa: course.id } do %>
                  <%= link_to course.name, course_path(course), class: "grey-text text-lighten-3" %>
                <% end %>
              <% end %>
            </ul>
          <% end %>
        </p>
      </div>
    </div>
  </div>
</div>